---
all:
  children:
    a:
      children:
        a_web:
          hosts:
            a_web1:
              ansible_host: 100.115.92.206
        a_ap:
          hosts:
            a_ap1:
              ansible_host: 100.115.92.206
    b:
      children:
        b_web:
          hosts:
            b_web1:
              ansible_host: 100.115.92.197
        b_ap:
          hosts:
            b_ap1:
              ansible_host: 100.115.92.197
    c:
      children:
        c_web:
          hosts:
            c_web1:
              ansible_host: 100.115.92.200
        c_ap:
          hosts:
            c_ap1:
              ansible_host: 100.115.92.200
    d:
      children:
        d_web:
          hosts:
            d_web1:
              ansible_host: 100.115.92.201
        d_ap:
          hosts:
            d_ap1:
              ansible_host: 100.115.92.201
