---
# TODO: これはすべてスタブです。
- name: Deploy xsystem.service
  ansible.builtin.template:
    src: x.service.j2
    dest: "/etc/systemd/system/stub_{{ item.name }}.service"
    mode: '0644'
  loop: "{{ ap_stubs }}"

- name: Create html dir
  ansible.builtin.file:
    path: "/usr/local/stub/stub_{{ item.name }}/{{ item.name }}"
    state: directory
    mode: '0755'
  loop: "{{ ap_stubs }}"

- name: Deploy html
  ansible.builtin.template:
    src: index.html.j2
    dest: "/usr/local/stub/stub_{{ item.name }}/{{ item.name }}/index.html"
    mode: '0644'
  loop: "{{ ap_stubs }}"

- name: Daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start stub servers
  ansible.builtin.systemd:
    name: "stub_{{ item.name }}.service"
    state: started
    enabled: true
  loop: "{{ ap_stubs }}"
